AirlinesWay.Api/Models/ErrorViewModel.cs
namespace AirlinesWay.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AirlinesWay.Api/Controllers/AirCompanyController.cs
using AirlinesWay.Application.Abstraction;
using AirlinesWay.Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AirlinesWay.Controllers;

public class AirCompanyController : Controller {
    private readonly IAirCompanyService _airCompanyService;
    private readonly IAirlineService _airlineService;

    public AirCompanyController(IAirCompanyService airCompanyService, IAirlineService airlineService) {
        _airCompanyService = airCompanyService;
        _airlineService = airlineService;
    }

    public async Task<IActionResult> Index() {
        var airLines = await _airlineService.GetAllAirLines();
        
        var selectList = new List<SelectListItem>();
        var response = new AirCompanyResponseModel();
        
        foreach (var airline in airLines)
        {
            selectList.Add(new()
            {
                Text = airline.Name,
                Value = airline.Id.ToString()
            });
        }
        
        return View(new AirCompanyResponseModel
        {
            Airlines = selectList
        });
    }
    
    [HttpPost]
    public async Task<IActionResult> AddAirCompany(AirCompanyResponseModel request) {
        var response = await _airCompanyService.AddAirCompany(request);
        return Ok(response);
    }
}

AirlinesWay.Api/Controllers/AirLineController.cs
using AirlinesWay.Application.Abstraction;
using AirlinesWay.Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AirlinesWay.Controllers;

public class AirLineController : Controller {
    private readonly IAirlineService _airlineService;

    private readonly ICityService _cityService;
    // GET
    public AirLineController(IAirlineService airlineService, ICityService cityService) {
        _airlineService = airlineService;
        _cityService = cityService;
    }

    [HttpGet("Index")]
    public async Task<IActionResult> Index() {
        var cities = await _cityService.GetAllCities();
        
        var selectList = new List<SelectListItem>();
        var response = new CitiesResponseModel();
        
        foreach (var city in cities)
        {
            selectList.Add(new()
            {
                Text = city.Name,
                Value = city.Id.ToString()
            });
        }
        
        return View(new AirLineRequestModel()
        {
            Cities = selectList
        });
    }
    
    [HttpPost("AddAirline")]
    public async Task<IActionResult> AddAirline(AirLineRequestModel request) {
        var response = await _airlineService.AddAirLine(request);
        return Ok(response);
    }
}

AirlinesWay.Api/Controllers/CitiesController.cs
using AirlinesWay.Application.Abstraction;
using AirlinesWay.Application.Models;
using AirlinesWay.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AirlinesWay.Controllers;

public class CitiesController : Controller
{
    private readonly ICityService _cityService;
    // GET
    public CitiesController(ICityService cityService)
    {
        _cityService = cityService;
    }

    [HttpGet]
    public async Task<IActionResult> Index(dynamic cityId)
    {
        var citiesResponse = await _cityService.GetAllCities();

        var selectList = new List<SelectListItem>();
        var response = new CitiesResponseModel();
        
        foreach (var city in citiesResponse)
        {
            selectList.Add(new()
            {
                Text = city.Name,
                Value = city.Id.ToString()
            });
        }

        response.Cities = selectList;
        
        return View(response);
    }

    [HttpPost("AddCity")]
    public async Task<IActionResult> AddCity(string cityName, int countryId)
    {
        var response = await _cityService.AddCityAsync(cityName, countryId);
        
        return View(response);
    }
}

AirlinesWay.Api/Controllers/CountriesController.cs
using AirlinesWay.Application.Abstraction;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWay.Controllers;

public class CountriesController : Controller
{
    private readonly ICountryService _countryService;
    // GET
    public CountriesController(ICountryService countryService)
    {
        _countryService = countryService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var response = await _countryService.GetAllCountries();
        return View(response);
    }

    [HttpPost("AddCity")]
    public async Task<IActionResult> AddCity(string cityName, string code)
    {
        var response = await _countryService.AddCountryAsync(cityName, code);
        return View(response);
    }
}

AirlinesWay.Api/Controllers/FlightsController.cs
using AirlinesWay.Application.Abstraction;
using AirlinesWay.Application.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AirlinesWay.Controllers;

public class FlightsController : Controller {
    private readonly IFlightService _flightService;
    private readonly IAirCompanyService _airCompanyService;
    private readonly IAirlineService _airlineService;

    public FlightsController(IFlightService flightService, IAirlineService airlineService, IAirCompanyService airCompanyService) {
        _flightService = flightService;
        _airlineService = airlineService;
        _airCompanyService = airCompanyService;
    }

    // GET
    public async Task<IActionResult> Index()
    {
        var aircompanies = await _airCompanyService.GetAllAirCompanies();
        var airLines = await _airlineService.GetAllAirLines();

        List<SelectListItem> selectAirCompaniesList;

        selectAirCompaniesList = airLines.Any() ? aircompanies.
            Select(airCompany => new SelectListItem() {Text = airCompany.Name, Value = airCompany.Id.ToString()}).ToList() : new List<SelectListItem>();

        return View(new FlightRequestModel()
        {
            AirCompanies = selectAirCompaniesList,
            AirLines = airLines
        });
    }

    [HttpPost]
    public IActionResult GetOptimizedFights(CitiesResponseModel request) {
        var result =
            _flightService.GetOptimizeFlight(new FlightGetOptimizeWayModel(request.StartedCityId, request.FinishedCityId,
                request.FilterType));

        return View(result);
    }
    
    [HttpPost("AddFLight")]
    public async Task<IActionResult> AddFlight(FlightRequestModel request)
    {
         request.ExpectedFinishDateTime = new DateTime(1987,1,1);
        var response = await _flightService.AddFlight(request);
        
        return Ok(response);
    }
}

AirlinesWay.Api/Pages/Countries/AddCity.cshtml
@model bool

@{
    ViewBag.Title = "Add City";
}

<h2>Add City</h2>
<form method="post">
    <p><label>Name</label><br />
        <input name="name" />
    </p>
    <p>
        <label>Country:</label><br />
        <input name="age" type="number" />
    </p>
    <input type="submit" value="Отправить" />
</form>

AirlinesWay.Api/Pages/Countries/Index.cshtml
@model System.Collections.Generic.IEnumerable<AirlinesWay.Domain.Country>

@{
    ViewBag.Title = "title";
}

<h2>title</h2>

AirlinesWay.Api/Views/AirCompany/Index.cshtml
@model AirlinesWay.Application.Models.AirCompanyResponseModel

@{
    ViewBag.Title = "title";
}

<h2>Add AirCompany</h2>

@using (Html.BeginForm("AddAirCompany", "AirCompany", FormMethod.Post, new {id="frmRegister"})) {

    @Html.LabelFor(m => m.Name)
    @Html.TextBoxFor(m => m.Name)

    @Html.ListBoxFor(m => m.AirLineIds, Model.Airlines, "Select AirLines for AirCompany")

    <input type='Submit' value='Register' id= "btnRegister" />
}

AirlinesWay.Api/Views/AirLine/Index.cshtml
@model AirlinesWay.Application.Models.AirLineRequestModel

@{
    ViewBag.Title = "title";
}

<h2>Add AirLine</h2>

@using (Html.BeginForm("AddAirline", "AirLine", FormMethod.Post, new {id="frmRegister"})) {

    @Html.LabelFor(m => m.Name)
    @Html.TextBoxFor(m => m.Name)

    @Html.DropDownListFor(m => m.StartedCityId, Model.Cities, "Select Started City")
    @Html.DropDownListFor(m => m.IntermediateCityId, Model.Cities, "Select Intermediate City")
    @Html.DropDownListFor(m => m.FinishedCityId, Model.Cities, "Select Finished City")

    @Html.LabelFor(m => m.Distance)
    @Html.TextBoxFor(m => m.Distance)

    <input type='Submit' value='Register' id= "btnRegister" />
}

AirlinesWay.Api/Views/Cities/AddCity.cshtml
@model bool

@{
    ViewBag.Title = "title";
}

<h2>title</h2>

AirlinesWay.Api/Views/Cities/Index.cshtml
@model AirlinesWay.Application.Models.CitiesResponseModel
@* @model AirlinesWay.Application.Models.FlightGetOptimizeWayModel *@

@{
    ViewBag.Title = "title";
}

@using (Html.BeginForm("GetOptimizedFights", "Flights", FormMethod.Post))
{
    <div class="form-group">
        <label class="control-label">Select Started City</label>
        @Html.DropDownListFor(m => m.StartedCityId,Model.Cities)

        <label class="control-label">Select Finished City</label>
                @Html.DropDownListFor(m => m.FinishedCityId, Model.Cities)
        
        <label class="control-label">Which method do you select for optimize rows</label>
                        @Html.DropDownListFor(m => m.FilterType, new SelectListItem[]
    {
        new ()
        {
            Text = "By Value",
            Value = "1"
        },
        new ()
        {
            Text = "By Time Duration",
            Value = "2"
        },
        new ()
        {
            Text = "By Road Length",
            Value = "3"
        }
    })
        <text> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</text>
            <td>@Html.ActionLink("Please Add AirLines", "Index", "AirLine")</td>
        <text> &nbsp; &nbsp;</text>
        <td>@Html.ActionLink("Please Add AirCompany", "Index", "AirCompany")</td>
        <text> &nbsp; &nbsp;</text>
                <td>@Html.ActionLink("Please Add Flights", "Index", "Flights")</td>
    </div>

    <button type="submit">Find</button>
}

AirlinesWay.Api/Views/Flights/GetOptimizedFights.cshtml
@model AirlinesWay.Application.Models.FlightResponseModel

@{
    ViewBag.Title = "title";
}

<h2>Optimized Flight</h2>

@if (@Model.Id > 0) {
    <table>  
        <tr>  
            <th>Id</th> 
            <th>Name</th>  
            <th>Code</th>  
            <th>Price</th>  
            <th>Airline Name</th> 
            <th>Airline Distance</th> 
            <th>AirCompanyName</th> 
            <th>TimeDuration</th> 
            <th>StartDateTime</th> 
            <th>ExpectedFinishDateTime</th> 
        </tr>  
        <tr>  
            <td>@Model.Id</td>  
            <td>@Model.Name</td>  
            <td>@Model.Code</td>  
            <td>@Model.Price</td>  
            <td>@Model.AirlineResponse.Name</td>  
            <td>@Model.AirlineResponse.Distance</td>  
            <td>@Model.AirCompanyName</td>  
            <td>@Model.TimeDuration</td>  
            <td>@Model.StartDateTime</td>  
            <td>@Model.ExpectedFinishDateTime</td>  
        </tr>  
    </table> 
}
else {
    <h3>Flights not found by requested cities</h3>
}

AirlinesWay.Api/Views/Flights/Index.cshtml
@model AirlinesWay.Application.Models.FlightRequestModel

@{
    ViewBag.Title = "title flights";
}

<h2>Add Flight</h2>

@using (Html.BeginForm("AddFlight", "Flights", FormMethod.Post, new {id="frmRegister"})) {

    @Html.DropDownListFor(m => m.AirCompanyId, Model.AirCompanies, "Select AirCompany")

    @Html.DropDownListFor(m => m.AirlineId, Model.AirLines.Select(x => new SelectListItem() {
        Text = x.Name,
        Value = x.Id.ToString()}))

    @Html.LabelFor(m => m.Name)
    @Html.TextBoxFor(m => m.Name)

    @Html.LabelFor(m => m.Code)
    @Html.TextBoxFor(m => m.Code)

    @Html.LabelFor(m => m.StartDateTime)
    @Html.TextBoxFor(model => model.StartDateTime, new { type = "datetime" })
    
    @Html.LabelFor(m => m.TimeDuration)
    @Html.TextBoxFor(model => model.TimeDuration)

    @Html.LabelFor(m => m.Price)
    @Html.TextBoxFor(m => m.Price)

<input type='Submit' value='Register' id= "btnRegister" />
}

AirlinesWay.Api/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>